image: ubuntu:latest

stages:
  - test

before_script:
  - apt-get update
  - apt-get install -y emacs-nox

emacs-config-tests:
  stage: test
  script:
    - emacs --version
    - emacs -Q --batch -l test/smoke-parse-config.el
    - emacs -Q --batch -L test -l test/run-tests.el
