
(defun sweyla480526 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/480526/"
  (interactive)
  (color-theme-install
   '(sweyla480526
     ((background-color . "#FFFFFB")
      (foreground-color . "#000000")
      (background-mode . bright)
      (border-color . "#C8C8C8")
      (cursor-color . "#000000")
      (mouse-color . "#C8C8C8"))
     (mode-line ((t (:foreground "#000000" :background "#C8C8C8"))))
     (region ((t (:background "#C8C8C8"))))

     (font-lock-comment-face ((t (:foreground "#6C8F20"))))
     (font-lock-constant-face ((t (:foreground "#008C00"))))
     (font-lock-builtin-face ((t (:foreground "#300259"))))
     (font-lock-function-name-face ((t (:foreground "#2B734A"))))
     (font-lock-variable-name-face ((t (:foreground "#21FF05"))))
     (font-lock-keyword-face ((t (:foreground "#002FB6"))))
     (font-lock-string-face ((t (:foreground "#008945"))))
     (font-lock-doc-string-face ((t (:foreground "#008945"))))
     (font-lock-type-face ((t (:foreground "#109C00"))))
     )))

(provide 'sweyla480526)
