
(defun sweyla858174 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/858174/"
  (interactive)
  (color-theme-install
   '(sweyla858174
     ((background-color . "#000006")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#0CF5FF"))))
     (font-lock-constant-face ((t (:foreground "#BCF1C7"))))
     (font-lock-builtin-face ((t (:foreground "#00D257"))))
     (font-lock-function-name-face ((t (:foreground "#22FFFF"))))
     (font-lock-variable-name-face ((t (:foreground "#00EC82"))))
     (font-lock-keyword-face ((t (:foreground "#CAA7F6"))))
     (font-lock-string-face ((t (:foreground "#6996FF"))))
     (font-lock-doc-string-face ((t (:foreground "#6996FF"))))
     (font-lock-type-face ((t (:foreground "#FEFFF7"))))
     )))

(provide 'sweyla858174)
