;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-or-beginning
        comment-or-uncomment-region
        indent-for-tab-command
        isearch-backward-regexp
        isearch-forward-regexp
        isearch-printing-char
        isearch-repeat-backward
        kill-region
        kill-start-of-line
        markdown-end-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        org-yank
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        markdown-outdent-or-delete
        ))
