;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-or-beginning
        indent-for-tab-command
        isearch-backward-regexp
        isearch-forward-regexp
        kill-region
        kill-start-of-line
        org-delete-char
        org-end-of-line
        org-kill-line
        org-self-insert-command
        org-yank
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        ))
